# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5430:5432
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379